### ISSUE TITLE
Alert notifications are lost when grafana restarts

### ISSUE THREAD

**Issue by suj-krishnan** [grafana/alerting#156] opened 2024-01-30 10:14 UTC
**What you expected to happen:**
When Grafana restarts, Alertmanager which handles the notifications, loses all alerts but keeps only the status which is whether it was alerting or resolved and the time when it happened (it's called notification log) but does not have any knowledge of pending notifications at the time of restart. To repopulate the Alertmanager, it can take up to 2 -3 evaluation intervals of a rule.

**What you expected to happen:**
It would help if the AlertManager keeps a history of pending notifications and sends them after it restarts (or after the first rule evaluation if the alert is still firing).

**Environment:**
Grafana version: 10.2.2

**Comment by armandgrillet** [comment] 2024-02-08 16:37
Duplicate of https://github.com/grafana/grafana/issues/68162

**Closed as completed by armandgrillet** 2024-02-08 16:37 UTC
